name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a4f7b3c9d0d3f2c5c51f7a2fae1b6e1e9e28a3f6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1d0bba4d9c6e2a4d8e7f4b1a5d8c2b4d4a6c8a9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your preferred region

      - name: Setup Node.js
        uses: actions/setup-node@b1d7e9f4c3a2b6e4c1d8a9f1e6b3c3a7d8e9f2b1
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS Lambda
        run: serverless deploy

