service: cybacad-backend
frameworkVersion: '4.18.2'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1  # You can change this to eu-west-2 if needed

functions:
  api:
    handler: server.api
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

plugins:
  - serverless-offline



