AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  CybAcadApiFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: server.api
      Runtime: nodejs18.x
      CodeUri: .
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  # This is the new resource to automatically deploy the API
  CybAcadApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: CybAcadApiFunction
    Properties:
      RestApiId:
        Ref: CybAcadApi
      StageName: dev